# Generated by Django 6.0.1 on 2026-03-17 11:17


from django.db import migrations

def seed_roles(apps,schema_editor):
    Role = apps.get_model('common', 'Role')
    role_types = ['ATTACK','DEFEND','HEAL','BUFF','SUPPORT','SEARCH']
    Role.objects.bulk_create([
        Role(role=r) for r in role_types
    ])

def reverse_seed_roles(apps,schema_editor):
    Role = apps.get_model('common', 'Role')
    Role.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial')
    ]

    operations = [
        migrations.RunPython(seed_roles, reverse_seed_roles)
    ]
