# Generated by Django 6.0.1 on 2026-03-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pictures'),
        ),
    ]
