# Generated by Django 6.0.1 on 2026-03-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='image_url',
            new_name='picture',
        ),
    ]
