# Generated by Django 6.0.1 on 2026-03-20 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userbattlestats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbattlestats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
